title: Aicha BOKBOT # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science master student @ Ecole Polytechnique and HEC Paris. Passionate about solving business problem using data science techniques.
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/aichabokbot/">View My LinkedIn Profile</a> 
  <a href="https://github.com/aichabokbot">View My Github Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
